### ISSUE TITLE
圧力制御について

### ISSUE THREAD

**Issue by EEprotocol** [LiMe-NanoBioeng/Arduino-to-DAQ#4]
圧力制御はきほんDACを通して行うんだけど，このときのDuty比は半固定抵抗器とか使って外部から可変にしたいかもしれない．
現状何も実装していないけど．

**Comment by JunichiMurai** [comment]
ほげ

**Comment by EEprotocol** [comment]
取敢えず実装するなら，数値固定で実装かな．

**Comment by JunichiMurai** [comment]
暇だったらやっとく　急ぎならやってほぢい

**Comment by EEprotocol** [comment]
全然全く急いでいないがとりあえずやっておく

**Comment by EEprotocol** [comment]
branch pressurepin を切っておいたのでプルリクします．
